### ISSUE TITLE
[FEATURE] Implement a rate-limiter for API calls

### ISSUE THREAD

**Issue by Moongazer** [clicksports/lexoffice-php-api#119]
Not sure if this should be a feature inside this library, or if a rate-limit is more a task for the custom API-client implementation. We've implemented the rate-limit using `symfony/rate-limiter` with token-bucket limiter which works amazing. Little downside is, that our API-service needs to implement the logic right before each API request (e.g. `$this->api->voucher()->create($data);`). So it's a bit of repeating-code always adding the check before each API request.

Because the LexOffice API introduces the rate-limit for everyone, maybe it makes sense to have it implemented inside this library (including configuration options in case there will be different limits for different plans in the future, or to disable it entirely). We think a good place would be in `Api::getResponse()`, right before `$this->client->send($this->request)`?!

Any feedback appreciated.

**Comment by Sysix** [comment]
Hello @Moongazer,

that is a great Idea to implement it, But we are trying to not bloat the library too much.
In the 1.0-dev branch the caching is already removed. 

The reason behind is, that `guzzlehttp/guzzle` has already middlewares which support each use case.
You can pass a `\GuzzleHttp\Client` as the second Parameter of your `\Clicksports\LexOffice\Api` Instance.

There you have choices of the `guzzle` community like following packages:

- [guzzle-cache-middleware](https://github.com/Kevinrob/guzzle-cache-middleware)
- [guzzle-rate-limiter-middleware](https://github.com/spatie/guzzle-rate-limiter-middleware)

And other great middlewares from other contributors :)

**Comment by Moongazer** [comment]
Hey @Sysix 
thanks for your fast response, and I fully agree to keep it slim as possible without any dependencies (didn't thought of that).
Also I didn't know that such features are available as Guzzle middleware, how awesome! Are there any plans when to release v1.0?

**Comment by Sysix** [comment]
>  Are there any plans when to release v1.0?

Not yet. I can't provide at the moment more information
