### ISSUE TITLE
Thank you and a question regarding caching

### ISSUE THREAD

**Issue by PercyDwn** [clicksports/lexoffice-php-api#131]
First of all a big thank you for the continuous work on the client! Nice to see the update to 1.0.

I have a general question regarding caching:
In the previous version I used a cache interface as recommended with a lifetime of 3600 seconds.
But I quickly ran into a problem: e.g. when updating a contact via the api, on following get requests I received the old data, as it was still cached. Therefore I disabled the cache, which is not ideal. How must I proceed in such a case; how can I clean the cache? Any advice?

Thanks in advance!

**Comment by Sysix** [comment]
Hello @PercyDwn thanks for the appreciation,

you can not  be sure that the cached version is the newest one. When you are updating an entity you don't know which Endpoints should be updated (specially with filterable endpoints).  
Also you can possible update the entity with the offical browser client.

My suggestion is to lower the lifetime of the cache. Problably 60 sec. So you still hitting the cache when you reload the page or 2 or more users are requesting the same Uri.

Alternative: tell your user the timestamp of the cache and give them an option to manually delete it. In the perfect world only the one request should be deleted from the cache.

**Comment by PercyDwn** [comment]
>My suggestion is to lower the lifetime of the cache. Problably 60 sec

I guess a lower lifetime would be sensible. 

> Also you can possible update the entity with the offical browser client.

That was actually the problem I had. We sync the contacts between our software and lexoffice. So we push updates if the contact is updated on our side and pull the data, when it is updated in lexoffice.
But when the contact changed event was recevied from lexoffice, the contact::get method would likely return a cached version of the data. I guess its reasonable to deactivate the cache interface on the event controller, entirely.

**Comment by Sysix** [comment]
> I guess a lower lifetime would be sensible.

A cache with a low lifetime is still better then no cache at all ;) 

> I guess its reasonable to deactivate the cache interface on the event controller, entirely.

Depending on the scale of software it can probably takes some time. Don't forget that the [Request timeout is 5sec](https://developers.lexoffice.io/docs/#event-subscriptions-endpoint-purpose). Maybe you need to put it also in a queue.

Hope I could get  uso some ideas. I will close this issue now, because it is not directly related to this package.
