### ISSUE TITLE
Composer Install fails with Symfony 5.1.x

### ISSUE THREAD

**Issue by rene-gates** [clicksports/lexoffice-php-api#15]
Hello,

I tried to install the package with the command from the readme file:
composer require clicksports/lex-office-api

The project is a Symfony 5.1.x project. 

The output is the following. Is the lexoffice-php-api package compatible with Guzzlehttp 7.2.0? And if so, how to install it?

Thanks

Using version ^0.11.0 for clicksports/lex-office-api
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for clicksports/lex-office-api ^0.11.0 -> satisfiable by clicksports/lex-office-api[0.11.0].
    - Conclusion: remove guzzlehttp/guzzle 7.2.0
    - Conclusion: don't install guzzlehttp/guzzle 7.2.0
    - clicksports/lex-office-api 0.11.0 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[6.3.0, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.3.1, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.3.2, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.3.3, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.4.0, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.4.1, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.0, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.1, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.2, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.3, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.4, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 7.2.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0) -> satisfiable by guzzlehttp/guzzle[7.2.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by Sysix** [comment]
Hello Thanks for your report!

Indeed I didnt define support for guzzle 7.
I will try to test it next week and release an update.

**Comment by rene-gates** [comment]
Thanks for the fix - when will you release it?

**Comment by Sysix** [comment]
release [v0.12.0](https://github.com/clicksports/lexoffice-php-api/releases/tag/0.12.0) is out there
