### ISSUE TITLE
Can I get voucher list/Invoice list by Customer ID (specific customer )

### ISSUE THREAD

**Issue by taleemhussain** [clicksports/lexoffice-php-api#33]
I want to get a specific customer list of invoices, vouchers, and activities. Can we achieve this? 
I tried to filter but not work. @Sysix

**Comment by Sysix** [comment]
the lexoffice API has no support filtering by customer atm.
Read more about here what you can filter:
https://developers.lexoffice.io/docs/#voucherlist-endpoint-retrieve-and-filter-voucherlist
