### ISSUE TITLE
Install under Symfony 6.0 is not possible

### ISSUE THREAD

**Issue by simonsolutions** [clicksports/lexoffice-php-api#58]
I tried to upgrade Symfony 5.4 to 6.0, there this package prevented the upgrade, once I removed it the upgrade could be done. On a Symfony 6.0 installation the package installation fails:

Using version ^0.14.1 for clicksports/lex-office-api
./composer.json has been updated
Running composer update clicksports/lex-office-api
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires clicksports/lex-office-api ^0.14.1 -> satisfiable by clicksports/lex-office-api[0.14.1].
    - clicksports/lex-office-api 0.14.1 requires psr/cache ^1.0 -> found psr/cache[1.0.0, 1.0.1] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require clicksports/lex-office-api:*" to figure out if any version is installable, or "composer require clicksports/lex-office-api:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by Sysix** [comment]
Hello :)

thanks for the report. 
I released `0.14.2` today with the support for newer `psr/cache` package versions.
