### ISSUE TITLE
Add date filter options for voucherlist to reduce response size

### ISSUE THREAD

**Issue by klein0r** [clicksports/lexoffice-php-api#82]
Missing options (optional):

- voucherDateFrom
- voucherDateTo
- createdDateFrom
- createdDateTo
- updatedDateFrom
- updatedDateTo

in

https://github.com/clicksports/lexoffice-php-api/blob/e22446f2d9a35f4f17f6574b14f1f435e8d1996b/src/Voucherlist/Client.php#L49-L55

Documentation: https://developers.lexoffice.io/docs/#voucherlist-endpoint-retrieve-and-filter-voucherlist

The reason for this issue is, that I have more than 10000 vouchers in my lexoffice account. When requesting all of them, I get

```
Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `GET https://api.lexoffice.io/v1/voucherlist?page=100&size=100&sort=voucherNumber,DESC&voucherType=salesinvoice&voucherStatus=draft,open,paid,paidoff,voided,accepted,rejected` resulted in a `500 Internal Server Error` response:
 { "timestamp" : "2022-07-01T09:50:53.481+02:00", "status" : 500, "error" : "Internal Server Error", "path": "/v1/vouche (truncated...)
 in /lexoffice-scanner/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
```

I think this could be solved by reducing the result (I just need the last month).

Code:

```php
$client = $api->voucherlist();
$client->sortDirection = 'DESC';
$client->sortColumn = 'voucherNumber';
$client->types = [
    'salesinvoice'
];
$client->statuses = [
    'draft',
    'open',
    'paid',
    'paidoff',
    'voided',
    'accepted',
    'rejected'
];

$response = $client->getAll();
```

**Comment by klein0r** [comment]
It works with a hacky solution like this (appending an additional GET parameter by using the status array)

```php
    $client->statuses = [
        'draft',
        'open',
        'paid',
        'paidoff',
        'voided',
        'accepted',
        'rejected&voucherDateFrom=2022-01-01' // Hacky solution
    ];
```

**Comment by Sysix** [comment]
Hey, thanks for the report.

I already try to implement it, but didn't have time to test it.
You can try `composer require dev-1.0-dev` and look up this file:
https://github.com/clicksports/lexoffice-php-api/blob/1.0-dev/src/Clients/VoucherList.php

`DateTimeInterface` can be `DateTime` or `DateTimeImmutable`. 

I will try and release the version in the upcomming month.

**Comment by Sysix** [comment]
Hey @klein0r Im sorry that I didn't had time to release it. We found a little bug with the date format output.  
Also I'm not longer the maintainer of this project. @rene-mueller please have a look :)

**Comment by MLDMoritz** [comment]
Filtering seems like a common feature. I would recommend adding filters to all objects that support it.
