### ISSUE TITLE
I cannot create a contact

### ISSUE THREAD

**Issue by TysonOsore** [clicksports/lexoffice-php-api#83]
[08-Jul-2022 06:37:21 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.lexoffice.io/v1/contacts` resulted in a `400 Bad Request` response:
{"IssueList":[{"i18nKey":"missing_entity","source":"roles","type":"validation_failure"},{"i18nKey":"missing_entity","sou (truncated...)
 in /home/schwimms/public_html/lex/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

that is the error.

**Comment by Sysix** [comment]
Hello,

this is a validation error. the php code itself works fine.
Please look at the response `missing_entity: "source"`

**Comment by MLDMoritz** [comment]
@TysonOsore 

Pass roles like this:

```php
$roles = (new \stdClass());
$roles->customer = (new \stdClass());


/** @var Response $response */
$response = $this->lexoffice->contact()->create([
    'roles' => $roles,
    'version' => 0,
    'company' => [
        'name' => $account->name
    ],
    'name' => $account->name,
]);
```
